# Generated by Django 5.1.6 on 2025-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
    ]
