# Generated by Django 5.1.6 on 2025-04-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionplan_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('back_ground_jobs', 'Background Jobs'), ('bands', 'Bands')], max_length=50),
        ),
    ]
