# Generated by Django 5.1.6 on 2025-06-24 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_restrictedcountryuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('sepa_debit', 'SEPA Direct Debit'), ('ideal', 'iDEAL'), ('sofort', 'Sofort'), ('bancontact', 'Bancontact'), ('giropay', 'Giropay'), ('eps', 'EPS'), ('p24', 'Przelewy24'), ('alipay', 'Alipay'), ('wechat_pay', 'WeChat Pay'), ('grabpay', 'GrabPay'), ('afterpay', 'Afterpay'), ('klarna', 'Klarna'), ('affirm', 'Affirm'), ('mada', 'Mada'), ('unionpay', 'UnionPay')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('background_jobs', 'Background Jobs Professional'), ('bands', 'Bands')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentMethodSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('sepa_debit', 'SEPA Direct Debit'), ('ideal', 'iDEAL'), ('sofort', 'Sofort'), ('bancontact', 'Bancontact'), ('giropay', 'Giropay'), ('eps', 'EPS'), ('p24', 'Przelewy24'), ('alipay', 'Alipay'), ('wechat_pay', 'WeChat Pay'), ('grabpay', 'GrabPay'), ('afterpay', 'Afterpay'), ('klarna', 'Klarna'), ('affirm', 'Affirm'), ('mada', 'Mada'), ('unionpay', 'UnionPay')], max_length=20)),
                ('region', models.CharField(choices=[('us', 'United States'), ('eu', 'European Union'), ('uk', 'United Kingdom'), ('ca', 'Canada'), ('au', 'Australia'), ('sg', 'Singapore'), ('my', 'Malaysia'), ('ph', 'Philippines'), ('th', 'Thailand'), ('vn', 'Vietnam'), ('id', 'Indonesia'), ('cn', 'China'), ('jp', 'Japan'), ('kr', 'South Korea'), ('in', 'India'), ('br', 'Brazil'), ('mx', 'Mexico'), ('global', 'Global')], max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=4, default=0, help_text='Processing fee as percentage', max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed processing fee', max_digits=10)),
                ('stripe_payment_method_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region', 'payment_method'],
                'unique_together': {('payment_method', 'region', 'currency')},
            },
        ),
    ]
