# Generated by Django 5.1.6 on 2025-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_talentuserprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentmedia',
            name='country',
            field=models.CharField(default='country', max_length=25),
        ),
        migrations.AddField(
            model_name='talentmedia',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="The user's date of birth.", null=True, verbose_name='Date of Birth'),
        ),
    ]
