# Generated by Django 5.1.6 on 2025-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_talentmedia_country_talentmedia_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjobsprofile',
            name='country',
            field=models.CharField(default='country', max_length=25),
        ),
        migrations.AddField(
            model_name='backgroundjobsprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='backgroundjobsprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
