# Generated by Django 5.1.6 on 2025-04-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_band_bandmembership_band_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='profiles.band')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to='profiles.talentuserprofile')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitations', to='profiles.talentuserprofile')),
            ],
        ),
    ]
