# Generated by Django 5.1.6 on 2025-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_bandinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentuserprofile',
            name='aboutyou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
