# Generated by Django 5.1.6 on 2025-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_talentuserprofile_aboutyou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='account_type',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('free', 'Free')], default='free', max_length=10),
        ),
    ]
