# Generated by Django 5.1.6 on 2025-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_expressiveworker_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressiveworker',
            name='performer_type',
            field=models.CharField(choices=[('actor', 'Actor'), ('comparse', 'Comparse'), ('voice_actor', 'Voice Actor'), ('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('comedian', 'Comedian'), ('host', 'TV/Event Host'), ('narrator', 'Narrator'), ('puppeteer', 'Puppeteer'), ('other', 'Other Performer')], default='actor', max_length=50),
        ),
    ]
