# Generated by Django 5.1.6 on 2025-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_expressiveworker_performer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentmedia',
            name='is_test_video',
            field=models.BooleanField(default=False, help_text='Is this a required test video for actor/comparse?'),
        ),
        migrations.AddField(
            model_name='talentmedia',
            name='test_video_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Test video order (1-5)', null=True),
        ),
    ]
