# Generated by Django 5.1.6 on 2025-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_hybridworker_beard_color_hybridworker_beard_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressiveworker',
            name='face_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/face/'),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='full_body_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/full/'),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='mid_range_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/mid/'),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='face_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/face/'),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='full_body_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/full/'),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='mid_range_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/mid/'),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='face_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/face/'),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='full_body_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/full/'),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='mid_range_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/mid/'),
        ),
    ]
