# Generated by Django 5.1.6 on 2025-06-28 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_expressiveworker_face_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisticmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artisticmaterial',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='artisticmaterial',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='artisticmaterial',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artisticmaterial',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='backgroundjobsprofile',
            name='account_type',
            field=models.CharField(choices=[('back_ground_jobs', 'Background Jobs'), ('free', 'Free')], db_index=True, default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='backgroundjobsprofile',
            name='country',
            field=models.CharField(db_index=True, default='country', max_length=25),
        ),
        migrations.AlterField(
            model_name='backgroundjobsprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='backgroundjobsprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_index=True, default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_type',
            field=models.CharField(choices=[('musical', 'Musical Bands/Troupes'), ('theatrical', 'Theatrical Troupes'), ('stunt', 'Stunt/Performance Teams'), ('dance', 'Dance Troupes'), ('event', 'Event Squads')], db_index=True, default='musical', max_length=20),
        ),
        migrations.AlterField(
            model_name='band',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='costume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='costume',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='costume',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='costume',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='costume',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('evenings', 'Evenings Only'), ('weekends', 'Weekends Only')], db_index=True, default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='beard_color',
            field=models.CharField(blank=True, choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], db_index=True, default='brown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='beard_length',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('stubble', 'Stubble'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('other', 'Other')], db_index=True, default='none', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='body_type',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('slim', 'Slim'), ('muscular', 'Muscular'), ('average', 'Average'), ('plus_size', 'Plus Size'), ('other', 'Other')], db_index=True, default='average', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='distinctive_body_marks',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('tattoo', 'Tattoo'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('other', 'Other')], db_index=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='distinctive_facial_marks',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('mole', 'Mole'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('freckles', 'Freckles'), ('other', 'Other')], db_index=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown'), ('hazel', 'Hazel'), ('black', 'Black'), ('other', 'Other')], db_index=True, default='brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='eye_pattern',
            field=models.CharField(choices=[('normal', 'Normal'), ('protruding', 'Protruding'), ('sunken', 'Sunken'), ('almond', 'Almond'), ('round', 'Round'), ('other', 'Other')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='eye_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='eyebrow_pattern',
            field=models.CharField(choices=[('arched', 'Arched'), ('straight', 'Straight'), ('curved', 'Curved'), ('thick', 'Thick'), ('thin', 'Thin'), ('other', 'Other')], db_index=True, default='straight', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='face_shape',
            field=models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('long', 'Long'), ('other', 'Other')], db_index=True, default='oval', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='forehead_shape',
            field=models.CharField(choices=[('broad', 'Broad'), ('narrow', 'Narrow'), ('rounded', 'Rounded'), ('straight', 'Straight'), ('other', 'Other')], db_index=True, default='straight', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='hair_color',
            field=models.CharField(choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], db_index=True, default='brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='hair_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily'), ('bald', 'Bald'), ('other', 'Other')], db_index=True, default='straight', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='height',
            field=models.FloatField(db_index=True, default=0.0, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='lip_shape',
            field=models.CharField(choices=[('thin', 'Thin'), ('full', 'Full'), ('heart', 'Heart-shaped'), ('round', 'Round'), ('bow', "Cupid's Bow"), ('other', 'Other')], db_index=True, default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='mustache_color',
            field=models.CharField(blank=True, choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], db_index=True, default='brown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='mustache_length',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('stubble', 'Stubble'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('other', 'Other')], db_index=True, default='none', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='performer_type',
            field=models.CharField(choices=[('actor', 'Actor'), ('comparse', 'Comparse'), ('voice_actor', 'Voice Actor'), ('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('comedian', 'Comedian'), ('host', 'TV/Event Host'), ('narrator', 'Narrator'), ('puppeteer', 'Puppeteer'), ('other', 'Other Performer')], db_index=True, default='actor', max_length=50),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='skin_tone',
            field=models.CharField(choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('brown', 'Brown'), ('dark', 'Dark')], db_index=True, default='fair', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='voice_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('rough', 'Rough'), ('deep', 'Deep'), ('soft', 'Soft'), ('nasal', 'Nasal'), ('other', 'Other')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='weight',
            field=models.FloatField(db_index=True, default=0.0, help_text='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='years_experience',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('evenings', 'Evenings Only'), ('weekends', 'Weekends Only')], db_index=True, default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='beard_color',
            field=models.CharField(blank=True, choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], db_index=True, default='brown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='beard_length',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('stubble', 'Stubble'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('other', 'Other')], db_index=True, default='none', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='body_type',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('slim', 'Slim'), ('muscular', 'Muscular'), ('average', 'Average'), ('plus_size', 'Plus Size'), ('other', 'Other')], db_index=True, default='athletic', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='distinctive_body_marks',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('tattoo', 'Tattoo'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('other', 'Other')], db_index=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='distinctive_facial_marks',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('mole', 'Mole'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('freckles', 'Freckles'), ('other', 'Other')], db_index=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown'), ('hazel', 'Hazel'), ('black', 'Black'), ('other', 'Other')], db_index=True, default='brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='eye_pattern',
            field=models.CharField(choices=[('normal', 'Normal'), ('protruding', 'Protruding'), ('sunken', 'Sunken'), ('almond', 'Almond'), ('round', 'Round'), ('other', 'Other')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='eye_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='eyebrow_pattern',
            field=models.CharField(choices=[('arched', 'Arched'), ('straight', 'Straight'), ('curved', 'Curved'), ('thick', 'Thick'), ('thin', 'Thin'), ('other', 'Other')], db_index=True, default='straight', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='face_shape',
            field=models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('long', 'Long'), ('other', 'Other')], db_index=True, default='oval', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite Athlete')], db_index=True, default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='forehead_shape',
            field=models.CharField(choices=[('broad', 'Broad'), ('narrow', 'Narrow'), ('rounded', 'Rounded'), ('straight', 'Straight'), ('other', 'Other')], db_index=True, default='straight', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='hair_color',
            field=models.CharField(choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], db_index=True, default='brown', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='hair_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily'), ('bald', 'Bald'), ('other', 'Other')], db_index=True, default='straight', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='height',
            field=models.FloatField(db_index=True, default=0.0, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='hybrid_type',
            field=models.CharField(choices=[('model', 'Fashion/Commercial Model'), ('stunt_performer', 'Stunt Performer'), ('body_double', 'Body Double'), ('motion_capture', 'Motion Capture Artist'), ('background_actor', 'Background Actor'), ('specialty_performer', 'Specialty Performer'), ('other', 'Other Physical Performer')], db_index=True, default='model', max_length=50),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='lip_shape',
            field=models.CharField(choices=[('thin', 'Thin'), ('full', 'Full'), ('heart', 'Heart-shaped'), ('round', 'Round'), ('bow', "Cupid's Bow"), ('other', 'Other')], db_index=True, default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='mustache_color',
            field=models.CharField(blank=True, choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], db_index=True, default='brown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='mustache_length',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('stubble', 'Stubble'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('other', 'Other')], db_index=True, default='none', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='risk_levels',
            field=models.CharField(choices=[('low', 'Low Risk Only'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('extreme', 'Extreme Stunts')], db_index=True, default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='skin_tone',
            field=models.CharField(choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('brown', 'Brown'), ('dark', 'Dark')], db_index=True, default='fair', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='voice_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('rough', 'Rough'), ('deep', 'Deep'), ('soft', 'Soft'), ('nasal', 'Nasal'), ('other', 'Other')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='weight',
            field=models.FloatField(db_index=True, default=0.0, help_text='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='willing_to_relocate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='years_experience',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='memorabilia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='memorabilia',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='memorabilia',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='memorabilia',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memorabilia',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prop',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prop',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prop',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prop',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rareitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rareitem',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rareitem',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rareitem',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rareitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='is_about_yourself_video',
            field=models.BooleanField(db_index=True, default=False, help_text="Is this the 1-minute 'about yourself' video?"),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='is_test_video',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this a required test video for actor/comparse?'),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='name',
            field=models.CharField(db_index=True, default='Untitled Media', max_length=124),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='account_type',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('free', 'Free')], db_index=True, default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='city',
            field=models.CharField(db_index=True, default='city', max_length=25),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='country',
            field=models.CharField(db_index=True, default='country', max_length=25),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, help_text="The user's date of birth.", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_index=True, default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='talentuserprofile',
            name='profile_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_for_rent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends Only'), ('flexible', 'Flexible')], db_index=True, default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional'), ('expert', 'Expert')], db_index=True, default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='primary_category',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('cinematographer', 'Cinematographer'), ('director', 'Director'), ('editor', 'Video/Film Editor'), ('animator', 'Animator'), ('graphic_designer', 'Graphic Designer'), ('makeup_artist', 'Makeup Artist'), ('costume_designer', 'Costume Designer'), ('set_designer', 'Set Designer'), ('lighting_designer', 'Lighting Designer'), ('visual_artist', 'Visual Artist'), ('composer', 'Music Composer'), ('sound_designer', 'Sound Designer'), ('other', 'Other Visual Creator')], db_index=True, default='photographer', max_length=50),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='rate_range',
            field=models.CharField(choices=[('low', 'Budget Friendly'), ('mid', 'Mid-Range'), ('high', 'Premium'), ('negotiable', 'Negotiable')], db_index=True, default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='willing_to_relocate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='years_experience',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='artisticmaterial',
            index=models.Index(fields=['name', 'price'], name='profiles_ar_name_564ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='artisticmaterial',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_ar_is_for__3b75d2_idx'),
        ),
        migrations.AddIndex(
            model_name='artisticmaterial',
            index=models.Index(fields=['created_at', 'price'], name='profiles_ar_created_520ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjobsprofile',
            index=models.Index(fields=['account_type', 'gender'], name='profiles_ba_account_378a42_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundjobsprofile',
            index=models.Index(fields=['country', 'date_of_birth'], name='profiles_ba_country_b26b82_idx'),
        ),
        migrations.AddIndex(
            model_name='band',
            index=models.Index(fields=['band_type', 'location'], name='profiles_ba_band_ty_70deac_idx'),
        ),
        migrations.AddIndex(
            model_name='band',
            index=models.Index(fields=['created_at', 'band_type'], name='profiles_ba_created_ade2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='band',
            index=models.Index(fields=['name', 'band_type'], name='profiles_ba_name_0d40fc_idx'),
        ),
        migrations.AddIndex(
            model_name='costume',
            index=models.Index(fields=['name', 'price'], name='profiles_co_name_9277f4_idx'),
        ),
        migrations.AddIndex(
            model_name='costume',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_co_is_for__76e278_idx'),
        ),
        migrations.AddIndex(
            model_name='costume',
            index=models.Index(fields=['created_at', 'price'], name='profiles_co_created_b6701c_idx'),
        ),
        migrations.AddIndex(
            model_name='expressiveworker',
            index=models.Index(fields=['performer_type', 'years_experience'], name='profiles_ex_perform_d1a1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='expressiveworker',
            index=models.Index(fields=['hair_color', 'eye_color'], name='profiles_ex_hair_co_2575d0_idx'),
        ),
        migrations.AddIndex(
            model_name='expressiveworker',
            index=models.Index(fields=['height', 'weight'], name='profiles_ex_height_89f217_idx'),
        ),
        migrations.AddIndex(
            model_name='expressiveworker',
            index=models.Index(fields=['body_type', 'availability'], name='profiles_ex_body_ty_83a8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='expressiveworker',
            index=models.Index(fields=['created_at', 'performer_type'], name='profiles_ex_created_7fb2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='hybridworker',
            index=models.Index(fields=['hybrid_type', 'years_experience'], name='profiles_hy_hybrid__3072c0_idx'),
        ),
        migrations.AddIndex(
            model_name='hybridworker',
            index=models.Index(fields=['hair_color', 'eye_color', 'skin_tone'], name='profiles_hy_hair_co_fd8568_idx'),
        ),
        migrations.AddIndex(
            model_name='hybridworker',
            index=models.Index(fields=['height', 'weight'], name='profiles_hy_height_0a0860_idx'),
        ),
        migrations.AddIndex(
            model_name='hybridworker',
            index=models.Index(fields=['fitness_level', 'risk_levels'], name='profiles_hy_fitness_9dfd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='hybridworker',
            index=models.Index(fields=['body_type', 'availability'], name='profiles_hy_body_ty_d8f5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='hybridworker',
            index=models.Index(fields=['created_at', 'hybrid_type'], name='profiles_hy_created_c0d38d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name', 'price'], name='profiles_lo_name_2f9368_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_lo_is_for__1b42e4_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['created_at', 'price'], name='profiles_lo_created_b9fb12_idx'),
        ),
        migrations.AddIndex(
            model_name='memorabilia',
            index=models.Index(fields=['name', 'price'], name='profiles_me_name_06b392_idx'),
        ),
        migrations.AddIndex(
            model_name='memorabilia',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_me_is_for__3ac1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='memorabilia',
            index=models.Index(fields=['created_at', 'price'], name='profiles_me_created_f6173a_idx'),
        ),
        migrations.AddIndex(
            model_name='musicitem',
            index=models.Index(fields=['name', 'price'], name='profiles_mu_name_61315c_idx'),
        ),
        migrations.AddIndex(
            model_name='musicitem',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_mu_is_for__aa87ef_idx'),
        ),
        migrations.AddIndex(
            model_name='musicitem',
            index=models.Index(fields=['created_at', 'price'], name='profiles_mu_created_64e11e_idx'),
        ),
        migrations.AddIndex(
            model_name='prop',
            index=models.Index(fields=['name', 'price'], name='profiles_pr_name_d25e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='prop',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_pr_is_for__bcfc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='prop',
            index=models.Index(fields=['created_at', 'price'], name='profiles_pr_created_d91d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='rareitem',
            index=models.Index(fields=['name', 'price'], name='profiles_ra_name_6ba793_idx'),
        ),
        migrations.AddIndex(
            model_name='rareitem',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_ra_is_for__54b859_idx'),
        ),
        migrations.AddIndex(
            model_name='rareitem',
            index=models.Index(fields=['created_at', 'price'], name='profiles_ra_created_43812a_idx'),
        ),
        migrations.AddIndex(
            model_name='talentuserprofile',
            index=models.Index(fields=['account_type', 'is_verified'], name='profiles_ta_account_04a5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='talentuserprofile',
            index=models.Index(fields=['country', 'city'], name='profiles_ta_country_3d2a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='talentuserprofile',
            index=models.Index(fields=['gender', 'date_of_birth'], name='profiles_ta_gender_8749f3_idx'),
        ),
        migrations.AddIndex(
            model_name='talentuserprofile',
            index=models.Index(fields=['profile_complete', 'account_type'], name='profiles_ta_profile_9422b3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['name', 'price'], name='profiles_ve_name_33079b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_for_rent', 'is_for_sale'], name='profiles_ve_is_for__f7580e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_at', 'price'], name='profiles_ve_created_caef16_idx'),
        ),
        migrations.AddIndex(
            model_name='visualworker',
            index=models.Index(fields=['primary_category', 'experience_level'], name='profiles_vi_primary_990a10_idx'),
        ),
        migrations.AddIndex(
            model_name='visualworker',
            index=models.Index(fields=['years_experience', 'availability'], name='profiles_vi_years_e_594c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='visualworker',
            index=models.Index(fields=['rate_range', 'willing_to_relocate'], name='profiles_vi_rate_ra_dadc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='visualworker',
            index=models.Index(fields=['created_at', 'primary_category'], name='profiles_vi_created_f2cebe_idx'),
        ),
    ]
