# Generated by Django 5.1.6 on 2025-03-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='email_verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
