# Generated by Django 5.1.6 on 2025-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
