# Generated by Django 5.1.6 on 2025-06-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedmediapost',
            unique_together={('content_type', 'object_id')},
        ),
    ]
