# Generated by Django 5.1.6 on 2025-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_bandinvitation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.AddField(
            model_name='band',
            name='band_type',
            field=models.CharField(choices=[('musical', 'Musical Bands/Troupes'), ('theatrical', 'Theatrical Troupes'), ('stunt', 'Stunt/Performance Teams'), ('dance', 'Dance Troupes'), ('event', 'Event Squads')], default='musical', max_length=20),
        ),
    ]
