# Generated by Django 5.1.6 on 2025-04-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_thumbnail_to_talentmedia'),
        ('profiles', '0010_backgroundjobsprofile_account_type_bandmedia'),
    ]

    operations = [
    ]
