# Generated by Django 5.1.6 on 2025-05-10 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_20250426_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressiveworker',
            name='accents',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='acting_experience',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='exganras',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='performance_skill',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='performance_style',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='performance_videos',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='preferred_roles',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='special_skills',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='stage_presence',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='training',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='union_membership',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='vocal_range',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='acrobatic_skills',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='chest_size',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='dance_style',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='flexibility_level',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='hip_size',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='hyganras',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='jump_height',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='martial_arts_skills',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='performance_skill',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='performance_videos',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='preferred_roles',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='running_speed',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='special_skills',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='stunt_experience',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='training',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='waist_size',
        ),
        migrations.RemoveField(
            model_name='talentmedia',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='engagement_rate',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='influencer_niche',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='modeling_experience',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='piercing_locations',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='preferred_styles',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='preferred_work',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='shoe_size',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='viganras',
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='body_type',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('slim', 'Slim'), ('muscular', 'Muscular'), ('average', 'Average'), ('plus_size', 'Plus Size'), ('other', 'Other')], default='average', max_length=20),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown'), ('hazel', 'Hazel'), ('black', 'Black'), ('other', 'Other')], default='brown', max_length=20),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='hair_color',
            field=models.CharField(choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], default='brown', max_length=20),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='height',
            field=models.FloatField(default=0.0, help_text='Height in cm'),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='performer_type',
            field=models.CharField(choices=[('actor', 'Actor'), ('voice_actor', 'Voice Actor'), ('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('comedian', 'Comedian'), ('host', 'TV/Event Host'), ('narrator', 'Narrator'), ('puppeteer', 'Puppeteer'), ('other', 'Other Performer')], default='actor', max_length=50),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight in kg'),
        ),
        migrations.AddField(
            model_name='expressiveworker',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown'), ('hazel', 'Hazel'), ('black', 'Black'), ('other', 'Other')], default='brown', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='hair_color',
            field=models.CharField(choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], default='brown', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='height',
            field=models.FloatField(default=0.0, help_text='Height in cm'),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='hybrid_type',
            field=models.CharField(choices=[('model', 'Fashion/Commercial Model'), ('stunt_performer', 'Stunt Performer'), ('body_double', 'Body Double'), ('motion_capture', 'Motion Capture Artist'), ('background_actor', 'Background Actor'), ('specialty_performer', 'Specialty Performer'), ('other', 'Other Physical Performer')], default='model', max_length=50),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='risk_levels',
            field=models.CharField(choices=[('low', 'Low Risk Only'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('extreme', 'Extreme Stunts')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='skin_tone',
            field=models.CharField(choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('brown', 'Brown'), ('dark', 'Dark')], default='fair', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight in kg'),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualworker',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='primary_category',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('cinematographer', 'Cinematographer'), ('director', 'Director'), ('editor', 'Video/Film Editor'), ('animator', 'Animator'), ('graphic_designer', 'Graphic Designer'), ('makeup_artist', 'Makeup Artist'), ('costume_designer', 'Costume Designer'), ('set_designer', 'Set Designer'), ('lighting_designer', 'Lighting Designer'), ('visual_artist', 'Visual Artist'), ('composer', 'Music Composer'), ('sound_designer', 'Sound Designer'), ('other', 'Other Visual Creator')], default='photographer', max_length=50),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='rate_range',
            field=models.CharField(choices=[('low', 'Budget Friendly'), ('mid', 'Mid-Range'), ('high', 'Premium'), ('negotiable', 'Negotiable')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visualworker',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expressiveworker',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('evenings', 'Evenings Only'), ('weekends', 'Weekends Only')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('evenings', 'Evenings Only'), ('weekends', 'Weekends Only')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='body_type',
            field=models.CharField(choices=[('athletic', 'Athletic'), ('slim', 'Slim'), ('muscular', 'Muscular'), ('average', 'Average'), ('plus_size', 'Plus Size'), ('other', 'Other')], default='athletic', max_length=20),
        ),
        migrations.AlterField(
            model_name='hybridworker',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite Athlete')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualworker',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends Only'), ('flexible', 'Flexible')], default='full_time', max_length=20),
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
