# Generated by Django 5.1.6 on 2025-05-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_expressiveworker_accents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressiveworker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='expressiveworker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hybridworker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visualworker',
            name='country',
        ),
    ]
