# Generated by Django 5.1.6 on 2025-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_expressiveworker_beard_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridworker',
            name='beard_color',
            field=models.CharField(blank=True, choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], default='brown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='beard_length',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('stubble', 'Stubble'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('other', 'Other')], default='none', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='distinctive_body_marks',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('tattoo', 'Tattoo'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('other', 'Other')], default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='distinctive_facial_marks',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('mole', 'Mole'), ('scar', 'Scar'), ('birthmark', 'Birthmark'), ('freckles', 'Freckles'), ('other', 'Other')], default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='eye_pattern',
            field=models.CharField(choices=[('normal', 'Normal'), ('protruding', 'Protruding'), ('sunken', 'Sunken'), ('almond', 'Almond'), ('round', 'Round'), ('other', 'Other')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='eye_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='eyebrow_pattern',
            field=models.CharField(choices=[('arched', 'Arched'), ('straight', 'Straight'), ('curved', 'Curved'), ('thick', 'Thick'), ('thin', 'Thin'), ('other', 'Other')], default='straight', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='face_shape',
            field=models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('long', 'Long'), ('other', 'Other')], default='oval', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='forehead_shape',
            field=models.CharField(choices=[('broad', 'Broad'), ('narrow', 'Narrow'), ('rounded', 'Rounded'), ('straight', 'Straight'), ('other', 'Other')], default='straight', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='hair_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily'), ('bald', 'Bald'), ('other', 'Other')], default='straight', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='lip_shape',
            field=models.CharField(choices=[('thin', 'Thin'), ('full', 'Full'), ('heart', 'Heart-shaped'), ('round', 'Round'), ('bow', "Cupid's Bow"), ('other', 'Other')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='mustache_color',
            field=models.CharField(blank=True, choices=[('blonde', 'Blonde'), ('brown', 'Brown'), ('black', 'Black'), ('red', 'Red'), ('gray', 'Gray/Silver'), ('other', 'Other')], default='brown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='mustache_length',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('stubble', 'Stubble'), ('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('other', 'Other')], default='none', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hybridworker',
            name='voice_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('rough', 'Rough'), ('deep', 'Deep'), ('soft', 'Soft'), ('nasal', 'Nasal'), ('other', 'Other')], default='normal', max_length=20),
        ),
    ]
