# Generated by Django 5.1.6 on 2025-06-25 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseuser_is_dashboard_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
